### ISSUE TITLE
Fundamental data ingested in Zipline

### ISSUE THREAD

**Issue by octaviodelsueldo** [PacktPublishing/Algorithmic-Trading-with-Python-Cookbook#3]
Hi Jason, I would like to know if you know a way to ingest fundamental premium data from Nasdaq, Sharadar, fmp or other provider in Zipline. I saw that over all the book you use prices and volume as your source but in any case you use alternative data or fundamentals. It would be greatly appreciated.

Thanks

**Comment by jasonstrimpel** [comment]
Technically Zipline can handle any type of data but you need to write custom code to ingest it. I have noted the link to the instructions for creating the appropriate extension files for premium data. You would have to modify it to ingest fundamental data. I do not have any code written (yet); otherwise, I would share it.
